app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => 'web'], function () {
    Route::get('/', function () {
        return view('index');
    })->name('main');

    Route::get('/gérantdelieu', [
        'uses' => 'AppController@getGerantPage',
        'as' => 'gerant',
        'middleware' => 'roles',
        'roles' => ['Admin', 'Gerant']
    ]);

    Route::get('/prestataire', [
        'uses' => 'AppController@getPrestatairePage',
        'as' => 'prestataire',
        'middleware' => 'roles',
        'roles' => ['Admin', 'Prestataire']
    ]);

    Route::get('/admin', [
        'uses' => 'AppController@getAdminPage',
        'as' => 'admin',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('/admin/roles', [
        'uses' => 'RoleController@editrole',
        'as' => 'admin.roles'
        
    ]);

    Route::post('/admin/assign-roles', [
        'uses' => 'AppController@postAdminAssignRoles',
        'as' => 'admin.assign'
    ]);


    Route::get('/signup', [
        'uses' => 'AuthController@getSignUpPage',
        'as' => 'signup'
    ]);

    Route::post('/signup', [
        'uses' => 'AuthController@postSignUp',
        'as' => 'signup'
    ]);

    Route::get('/signin', [
        'uses' => 'AuthController@getSignInPage',
        'as' => 'signin'
    ]);

    Route::post('/signin', [
        'uses' => 'AuthController@postSignIn',
        'as' => 'signin'
    ]);

    Route::get('/logout', [
        'uses' => 'AuthController@getLogout',
        'as' => 'logout'
    ]);

        Route::resource('admin/users', 'UserController');

        Route::auth();

});



        

resources/views/admin/lieux/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Créer un nouvel utilisateur</h1>
			<hr>

			{!! Form::open(array(['route' => 'admin.users.store', 'data-parsley-validate' => '', 'onsubmit' => 'return confirm("Are you sure?")'])) !!}
				{{ Form::label('last_name', 'Nom:') }}
				{{ Form::text('last_name', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}
				

				{{ Form::label('first_name', 'Prénom:') }}
				{{ Form::text('first_name', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255') ) }}
				

				{{ Form::label('email', 'E-mail:') }}
				{{ Form::email('email', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255') ) }}
				

				{{ Form::label('password', 'Mot de passe:') }}
				{{ Form::text('password', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255') ) }}
				
				{{ csrf_field() }}
				<br/>
				{{ Form::submit('Créer', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;')) }}
			{!! Form::close() !!}
		</div>
</div>

@endsection

resources/views/admin/lieux/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
		{!! Form::model($user, ['route' => ['admin.users.update', $user->id], 'method' => 'PUT']) !!}
		<div class="col-md-8">
			{{ Form::label('last_name', 'Nom:') }}
			{{ Form::text('last_name', null, ["class" => 'form-control input-lg']) }}
			<p id="error_last_name" class="error"></p>

			{{ Form::label('first_name', 'Prénom:') }}
			{{ Form::text('first_name', null, ["class" => 'form-control input-lg']) }}
			<p id="error_first_name" class="error"></p>

			{{ Form::label('email', 'E-mail:') }}
			{{ Form::text('email', null, ["class" => 'form-control input-lg']) }}
			<p id="error_mail" class="error"></p>  
               

                   
			
		</div>

		<div class="col-md-4">

			<div class="well">

				<div class="row">

					<div class="col-sm-6">
						{!! Html::linkRoute('admin.users.show', 'Annuler', array($user->id), array('class' => 'btn btn-danger btn-block')) !!}
					</div>
					<div class="col-sm-6">
						{{ Form::submit('Enregistrer', ['class' => 'btn btn-success btn-block']) }}
					</div>
				</div>

			</div>
				
		</div>
{!! Form::close() !!}
<div id="Form_role">
	<form action="{{ route('admin.assign') }}" method="post">
			<td><input type="hidden" name="email" value="{{ $user->email }}"></td>
			{{ Form::label('user', 'Utilisateur') }}
			<td><input type="checkbox" {{ $user->hasRole('User') ? 'checked' : '' }} name="role_user"></td><br/>
			{{ Form::label('gerant', 'Gérant de lieu') }}
			<td><input type="checkbox" {{ $user->hasRole('Gerant') ? 'checked' : '' }} name="role_gerant"></td><br/>
			{{ Form::label('prestataire', 'Prestataire') }}
			<td><input type="checkbox" {{ $user->hasRole('Prestataire') ? 'checked' : '' }} name="role_prestataire"></td><br/>
			{{ Form::label('admin', 'Administrateur') }}
			 <td><input type="checkbox" {{ $user->hasRole('Admin') ? 'checked' : '' }} name="role_admin"></td><br/>
			 {{ csrf_field() }}
			 <td><button type="submit">Rôle assigné</button></td>
         </form>
</div>

@stop

resources/views/admin/lieux/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
		<div class="col-md-10">
			<h1>Tous les utilisateurs</h1>
		</div>

		<div class="col-md-2">
			<a href="{{ route('admin.users.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Ajouter un utilisateur</a>
		</div>
		<div class="col-md-12">
			<hr>
		</div>
	</div> <!-- end of .row -->

	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Email</th>
					
					<th></th>
				</thead>

				<tbody>
					
					@foreach ($users as $user)
						
						<tr>
							<th>{{ $user->last_name }}</th>
							<td>{{ $user->first_name }}</td>
							<td>{{ $user->email }}</td>
							
							<td><a href="{{ route('admin.users.show', $user->id) }}" class="btn btn-default btn-sm">Voir</a> <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-default btn-sm">Modifier</a></td>
						</tr>

					@endforeach

				</tbody>
			</table>

			<div class="text-center">
				{!! $users->links(); !!}
			</div>
		</div>
</div>

@endsection

resources/views/admin/lieux/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
		<div class="col-md-8">


			<div id="backend-comments" style="margin-top: 50px;">

				<table class="table">
					<thead>
						<tr>
							<th>Nom</th>
							<th>Prénom</th>
							<th>Email</th>
							<th width="70px"></th>
						</tr>
					</thead>
					<tr>
							<td>{{ $user->last_name }}</td>
							<td>{{ $user->first_name }}</td>
							<td>{{ $user->email }}</td>
					</tr>
				</table>
			</div>
		</div>

		<div class="col-md-4">
			<div class="well">
				
				<div class="row">
					<div class="col-sm-6">
						{!! Html::linkRoute('admin.users.edit', 'Modifier', array($user->id), array('class' => 'btn btn-primary btn-block')) !!}
					</div>
					<div class="col-sm-6">
						{!! Form::open(['route' => ['admin.users.destroy', $user->id], 'method' => 'DELETE']) !!}

						{!! Form::submit('Supprimer', ['class' => 'btn btn-danger btn-block']) !!}

						{!! Form::close() !!}
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						{{ Html::linkRoute('admin.users.index', '<< Voir tous les utilisateurs', array(), ['class' => 'btn btn-default btn-block btn-h1-spacing']) }}
					</div>
				</div>

			</div>
		</div>
	</div>


@endsection